### ISSUE TITLE
errors are shown after onChange

### ISSUE THREAD

**Issue by japrescott** [lookfirst/mui-rff#189] opened 2020-04-17 08:35 UTC
errors are shown as soon as a change occurs, not onBlur. e.g with email verficiation (using YUP). Also using the subscribe trick on final form set to 'submitting', errors popped up right away
Is this configurable in some way?

**Comment by lookfirst** [comment] 2020-04-17 14:10
Hi, thanks for the report, this is a duplicate of the discussion on #186 .

**Closed by lookfirst** 2020-04-17 14:10 UTC
Labels: duplicate
