### ISSUE TITLE
Validate On Blur issues with Autocomplete

### ISSUE THREAD

**Issue by servonlewis** [lookfirst/mui-rff#283] opened 2020-08-25 19:13 UTC
Hello all, first post for me!

I am getting an issue where if you set up validateOnBlur, on the Form, it works with all fields as expected, other than autocomplete.

If you blur on autocomplete, it will not remove the error until you validate another non autocomplete field.  

At first i though this was due to my large form with many Yup validations, but you can actually get the issue with the small code snippet below.

My question is, is this a fixable bug, or is there a better way to make my form faster?  Currently, typing in a textfield takes a very long time after introducing the makeValidation schema.

**To Reproduce**
1. Paste in the code snippet below, and try it out.

```typescript

import React from "react";
import { Checkbox as MuiCheckbox, Button } from "@material-ui/core";
import { Autocomplete, makeValidate, showErrorOnBlur } from "mui-rff";
import { Form } from "react-final-form";
import * as Yup from "yup";
const autocompleteData = [
  { label: "Earth", value: "earth" },
  { label: "Mars", value: "mars" },
  { label: "Venus", value: "venus" },
  { label: "Brown Dwarf Glese 229B", value: "229B" },
];

const onSubmit = async (values: any) => {
  console.log(values);
};

const schema = Yup.object().shape({
  planet: Yup.string().required(),
});
const validate = makeValidate(schema);

export const TestAutoComplete = () => (
  <Form
    initialValues={{ planet: "" }}
    onSubmit={onSubmit}
    validateOnBlur
    validate={validate}
    render={({ errors, handleSubmit }) => {
      console.log(errors);
      return (
        <form onSubmit={handleSubmit} noValidate>
          <Autocomplete
            label="Pick at least one planet"
            name="planet"
            options={autocompleteData}
            onBlur={() => console.log("blur")}
            showError={showErrorOnBlur}
            getOptionValue={(option) => option.value}
            getOptionLabel={(option) => option.label}
            disableCloseOnSelect={true}
            renderOption={(option, { selected }) => (
              <>
                <MuiCheckbox style={{ marginRight: 8 }} checked={selected} />
                {option.label}
              </>
            )}
          />
          <div style={{ marginTop: 50 }}>
            <Button type="submit">fdshifdhdshhsi</Button>
          </div>
        </form>
      );
    }}
  />
);

```

**Expected behavior**
When you blur, the error should appear or go away, based on the situation, currently, it'll stay on the error.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 84

**Comment by servonlewis** [comment] 2020-11-21 22:53
Is this library alive?

**Comment by lookfirst** [comment] 2020-11-21 23:05
Yep

**Comment by prog83** [comment] 2021-04-22 11:24
<img width="1023" alt="Снимок экрана 2021-04-22 в 14 23 51" src="https://user-images.githubusercontent.com/31012354/115706563-75a2bd00-a376-11eb-912f-67eebbffa18e.png">

**because there is no event handling input.onBlur**

**Comment by servonlewis** [comment] 2021-05-01 05:52
> 
> 
> <img width="1023" alt="Снимок экрана 2021-04-22 в 14 23 51" src="https://user-images.githubusercontent.com/31012354/115706563-75a2bd00-a376-11eb-912f-67eebbffa18e.png">
> 
> 
> 
> **because there is no event handling input.onBlur**

Sounds like something that I hope can be fixed. Any work around for such a thing?

**Comment by nitaking** [comment] 2021-08-17 07:59
My solution is using `formApi.blur`.

![image](https://user-images.githubusercontent.com/10850034/129687255-df4aa0e2-1e53-4a5e-851b-c84c0d5a9a7a.png)

I'll works!

```ts
onBlur={(e) => {
  formApi.blur(NAMES.transportCompanyCode);
}}
```

**Comment by lookfirst** [comment] 2021-08-17 21:57
I just tried to spend a few hours reproducing this and couldn't. If someone can come up with a clear testcase with the latest code, I'd love it.

**Comment by lookfirst** [comment] 2022-09-15 20:14
Closing, I suspect this isn't an issue any longer. Reopen if necessary!

**Closed by lookfirst** 2022-09-15 20:14 UTC
