### ISSUE TITLE
[bug] @material-ui/lab shouldn't be required when not using Autocomplete

### ISSUE THREAD

**Issue by depiction** [lookfirst/mui-rff#142] opened 2020-02-28 19:54 UTC
The readme says to run `yarn add mui-rff @material-ui/core @material-ui/pickers final-form react-final-form` to install all required dependencies. It also says to run `yarn add @material-ui/lab` if using Autocomplete. I created a basic login form using MUI-RFF with only the TextField (no Autocomplete).

`import { TextField } from "mui-rff";`

However, I got a compilation error when building my project.

`Module not found: Can't resolve '@material-ui/lab/Autocomplete' in '/node_modules/mui-rff/dist'`

I therefore had to install @material-ui/lab.

**Expected behavior**
@material-ui/lab shouldn't be required unless Autocomplete is imported from "mui-rff".

**Comment by lookfirst** [comment] 2020-02-28 20:06
Thanks for the report. I noticed this as well. If you have ideas on how to solve this short of building every single component as its own package, that would be great.

**Comment by depiction** [comment] 2020-02-29 00:24
Maybe @material-ui/lab could be included as an optional dependency in package.json, then import it using require() inside the Autocomplete function. See https://npm.github.io/using-pkgs-docs/package-json/types/optionaldependencies.html.

**Comment by lookfirst** [comment] 2020-02-29 00:36
Yea, that or a peerDependency. Would you like to experiment and tell me which one is best?

**Comment by kybarg** [comment] 2020-02-29 01:22
I would say this is duplicate of #138

**Comment by lookfirst** [comment] 2020-03-04 04:35
Optional seemed to work!

**Comment by lookfirst** [comment] 2020-03-04 04:51
This is actually not fixed...

**Comment by lookfirst** [comment] 2020-03-21 22:48
Storing this here for later consideration: https://github.com/pikapkg/pack

**Comment by lookfirst** [comment] 2020-03-21 22:49
Also: https://github.com/developit/microbundle

**Comment by martinrojas** [comment] 2022-06-13 22:10
Adding this here to document it. With a clean install in a new project. The `TextField` component brings up the following error `Error: Can't resolve '@mui/x-date-pickers'`

**Comment by lookfirst** [comment] 2022-09-15 20:10
Closing, haven't found a need to fix this in years...

**Closed by lookfirst** 2022-09-15 20:10 UTC
Labels: bug, good first issue
