### ISSUE TITLE
reset Autocomplete value

### ISSUE THREAD

**Issue by alexander-r-jaimy** [lookfirst/mui-rff#284] opened 2020-08-26 11:44 UTC
**Describe the bug**
I'm trying to figure out why reset in not working on the Autocomplete mui-rff.

**To Reproduce**
To reproduce the steps you can just open your oficial code sandbox, or follow this link:
https://codesandbox.io/s/react-final-form-material-ui-example-forked-wyz2p?file=/src/index.tsx

**Expected behavior**
When reset button is clicked, the value from Autocomplete input should also disappear.

**Additional context**
I'm unsure if this is a mui-rff problem, or autocomplete itself.
Please share you thoughs if you know how to reset values in mui-rff Autocomplete

**Comment by lookfirst** [comment] 2020-08-26 13:58
Dupe of #273 I think.

**Closed by lookfirst** 2020-08-26 13:58 UTC
Labels: duplicate
