### ISSUE TITLE
AutoComplete: RFF meta.active not set when user changes values

### ISSUE THREAD

**Issue by yann-combarnous** [lookfirst/mui-rff#739] opened 2022-05-06 09:28 UTC
**Describe the bug**
When using the AutoComplete component, the "meta.active" final form property is not set. 

It works fine in other components, such as Select or TextField.

**To Reproduce**

1. Go to Code Sandbox: https://codesandbox.io/s/old-http-0jz3dn?file=/src/App.js
2. Click on Currencies field (AutoComplete), modify value
3. look at console log, value of "active" field is "undefined"

**Expected behavior**
1. Go to Code Sandbox: https://codesandbox.io/s/old-http-0jz3dn?file=/src/App.js
2. Click on User field (TextField), modify value
3. look at console log, value of "active" field is "userName"

**Comment by lookfirst** [comment] 2022-05-08 04:35
Thanks for the report! Ok, I see that. I have zero clue on how to fix it though, do you?

**Comment by yann-combarnous** [comment] 2022-05-10 07:23
> Thanks for the report! Ok, I see that. I have zero clue on how to fix it though, do you?

Have not had a chance to take a look yet, started by doing a simple reproduction. 

I guess I would start by comparing the property list received by TextField in AutoComplete component vs the list in the standalone Textfield? I may give it a try later this week, if I get some time. Probably some onFocus listener missing?

**Comment by ErikParso** [comment] 2023-07-26 14:50
Hi any update on this issue?

**Comment by lookfirst** [comment] 2023-07-26 14:55
@ErikParso There is no update until someone decides to come along and help fix it, that's why the issue is still open and you're running across it. Since it is affecting you, would you like to take a stab at fixing it? I can offer whatever support you need to help you. By helping fixing this issue, you're helping out a lot of other developers and contributing something back to the community as a whole. This is a very positive feedback loop for everyone.

😄

**Comment by ErikParso** [comment] 2023-07-26 15:02
Yay everybody taking nobody giving :D Ill take a look

**Comment by ErikParso** [comment] 2023-07-26 19:30
https://github.com/lookfirst/mui-rff/pull/1079
Autocomplete field active meta state was not set bc input onFocus and and onBlur events were not utilized.

**Comment by lookfirst** [comment] 2023-07-28 00:03
fixed in 6.2.3. thanks @ErikParso for the pr!

**Closed by lookfirst** 2023-07-28 00:03 UTC
