### ISSUE TITLE
[feature] separate component exports

### ISSUE THREAD

**Issue by kybarg** [lookfirst/mui-rff#138] opened 2020-02-27 00:54 UTC
In order to minimize bundle size and skip import of unused components

Current behavior:
```javascript
import { Autocomplete } from 'mui-rff'
```

Desired behavior
```javascript
import { Autocomplete } from 'mui-rff'
// or
import Autocomplete from 'mui-rff/Autocomplete'
```

**Comment by lookfirst** [comment] 2020-02-27 02:06
Thanks for the report! =) I'm trying to understand these differences...

![image](https://user-images.githubusercontent.com/85355/75405461-a6967780-58c2-11ea-9bdd-bd54f1baf908.png)

**Comment by lookfirst** [comment] 2020-02-27 02:09
As for the packaging... javascript is extremely frustrating because there is 1000 ways to do everything and none of them are that good.

I'm open to ideas to make it better. Right now, I'm using tsdx, which uses parcel and it basically bundles everything into a single file. Tree shaking in your build _should_ be able to figure this stuff out, but alas my guess is that is something that won't work better until Parcel 2. 

The idea of splitting everything into separate builds doesn't sound very appealing.

So yea... open to ideas for sure...

**Comment by kybarg** [comment] 2020-02-27 16:08
> Thanks for the report! =) I'm trying to understand these differences...
> 
> ![image](https://user-images.githubusercontent.com/85355/75405461-a6967780-58c2-11ea-9bdd-bd54f1baf908.png)

in this case no difference😊
Just wanted to show that would be nice to leave single import (in case you use all components anyway) and also add separate imports

**Comment by kybarg** [comment] 2020-02-27 16:11
In general I want to be able to use separate wrappers.
Using the whole bundle of Date Pickers, Autocomplete etc, can significantly increase bundle size, when you only use TextField in your project

**Comment by lookfirst** [comment] 2020-02-27 16:23
Your build system should be able to tree shake things in the minimization phase.

**Comment by lookfirst** [comment] 2020-03-10 16:50
I'm going to close this issue. It is basically a duplicate of #142 at this point.

**Closed by lookfirst** 2020-03-10 16:50 UTC
Labels: duplicate, enhancement, good first issue
